### ISSUE TITLE
Fail to lauch vagrant on Linux (Pop-Os) - Vagrant fails to call VBoxManage

### ISSUE THREAD

**Issue by x-malet** [medmouine/vagrant-k3s-HA-cluster#1]
After installing vagrant with arkade, I was unable to lauch it and got the same error as [here](https://github.com/hashicorp/vagrant/issues/12088#issue-753614356). 

I had to remove the files and then, install vagrant like presented in the Vagrant Doc as follow:

```bash
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
sudo apt-get update && sudo apt-get install vagrant
```

**Comment by medmouine** [comment]
Closed for duplication.

Checkout [this issue](https://github.com/medmouine/vagrant-k3s-HA-cluster/issues/3) for follow up.
